name: "Lint and Test"

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/setup-yarn@v1
      - name: Run tests
        run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/setup-yarn@v1
      - name: Lint
        run: yarn lint:all
