name: "Lint and Test"

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/setup-yarn@v1
        with:
          flags: --immutable-cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install

      - name: Run tests
        run: yarn test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/setup-yarn@v1
        with:
          flags: --immutable-cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install

      - name: Lint
        run: yarn lint
